#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Inferme")]
public partial class DataClasses2DataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertCategory(Category instance);
  partial void UpdateCategory(Category instance);
  partial void DeleteCategory(Category instance);
  partial void InsertBlogg(Blogg instance);
  partial void UpdateBlogg(Blogg instance);
  partial void DeleteBlogg(Blogg instance);
  #endregion
	
	public DataClasses2DataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["InfermeConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Category> Categories
	{
		get
		{
			return this.GetTable<Category>();
		}
	}
	
	public System.Data.Linq.Table<Blogg> Bloggs
	{
		get
		{
			return this.GetTable<Blogg>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Category")]
public partial class Category : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _CategroyId;
	
	private string _CategoryName;
	
	private System.Nullable<System.DateTime> _createdate;
	
	private System.Nullable<System.DateTime> _updatedate;
	
	private string _createby;
	
	private string _updateby;
	
	private string _CategoryImage;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategroyIdChanging(int value);
    partial void OnCategroyIdChanged();
    partial void OnCategoryNameChanging(string value);
    partial void OnCategoryNameChanged();
    partial void OncreatedateChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedateChanged();
    partial void OnupdatedateChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedateChanged();
    partial void OncreatebyChanging(string value);
    partial void OncreatebyChanged();
    partial void OnupdatebyChanging(string value);
    partial void OnupdatebyChanged();
    partial void OnCategoryImageChanging(string value);
    partial void OnCategoryImageChanged();
    #endregion
	
	public Category()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategroyId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int CategroyId
	{
		get
		{
			return this._CategroyId;
		}
		set
		{
			if ((this._CategroyId != value))
			{
				this.OnCategroyIdChanging(value);
				this.SendPropertyChanging();
				this._CategroyId = value;
				this.SendPropertyChanged("CategroyId");
				this.OnCategroyIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="VarChar(15)")]
	public string CategoryName
	{
		get
		{
			return this._CategoryName;
		}
		set
		{
			if ((this._CategoryName != value))
			{
				this.OnCategoryNameChanging(value);
				this.SendPropertyChanging();
				this._CategoryName = value;
				this.SendPropertyChanged("CategoryName");
				this.OnCategoryNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdate", DbType="DateTime")]
	public System.Nullable<System.DateTime> createdate
	{
		get
		{
			return this._createdate;
		}
		set
		{
			if ((this._createdate != value))
			{
				this.OncreatedateChanging(value);
				this.SendPropertyChanging();
				this._createdate = value;
				this.SendPropertyChanged("createdate");
				this.OncreatedateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedate", DbType="DateTime")]
	public System.Nullable<System.DateTime> updatedate
	{
		get
		{
			return this._updatedate;
		}
		set
		{
			if ((this._updatedate != value))
			{
				this.OnupdatedateChanging(value);
				this.SendPropertyChanging();
				this._updatedate = value;
				this.SendPropertyChanged("updatedate");
				this.OnupdatedateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createby", DbType="VarChar(100)")]
	public string createby
	{
		get
		{
			return this._createby;
		}
		set
		{
			if ((this._createby != value))
			{
				this.OncreatebyChanging(value);
				this.SendPropertyChanging();
				this._createby = value;
				this.SendPropertyChanged("createby");
				this.OncreatebyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateby", DbType="VarChar(100)")]
	public string updateby
	{
		get
		{
			return this._updateby;
		}
		set
		{
			if ((this._updateby != value))
			{
				this.OnupdatebyChanging(value);
				this.SendPropertyChanging();
				this._updateby = value;
				this.SendPropertyChanged("updateby");
				this.OnupdatebyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryImage", DbType="VarChar(100)")]
	public string CategoryImage
	{
		get
		{
			return this._CategoryImage;
		}
		set
		{
			if ((this._CategoryImage != value))
			{
				this.OnCategoryImageChanging(value);
				this.SendPropertyChanging();
				this._CategoryImage = value;
				this.SendPropertyChanged("CategoryImage");
				this.OnCategoryImageChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Blogg")]
public partial class Blogg : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _BloggId;
	
	private string _BloggTitle;
	
	private string _BloggImage;
	
	private string _ShortDescription;
	
	private string _Description;
	
	private System.Nullable<int> _category;
	
	private System.Nullable<System.DateTime> _createdate;
	
	private string _createby;
	
	private System.Nullable<int> _Status;
	
	private System.Nullable<int> _createUserId;
	
	private System.Nullable<int> _SubCatagoryId;
	
	private System.Nullable<System.DateTime> _UpdateDatebyAdmin;
	
	private System.Nullable<int> _UpdateAdminId;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBloggIdChanging(int value);
    partial void OnBloggIdChanged();
    partial void OnBloggTitleChanging(string value);
    partial void OnBloggTitleChanged();
    partial void OnBloggImageChanging(string value);
    partial void OnBloggImageChanged();
    partial void OnShortDescriptionChanging(string value);
    partial void OnShortDescriptionChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OncategoryChanging(System.Nullable<int> value);
    partial void OncategoryChanged();
    partial void OncreatedateChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedateChanged();
    partial void OncreatebyChanging(string value);
    partial void OncreatebyChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OncreateUserIdChanging(System.Nullable<int> value);
    partial void OncreateUserIdChanged();
    partial void OnSubCatagoryIdChanging(System.Nullable<int> value);
    partial void OnSubCatagoryIdChanged();
    partial void OnUpdateDatebyAdminChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDatebyAdminChanged();
    partial void OnUpdateAdminIdChanging(System.Nullable<int> value);
    partial void OnUpdateAdminIdChanged();
    #endregion
	
	public Blogg()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloggId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int BloggId
	{
		get
		{
			return this._BloggId;
		}
		set
		{
			if ((this._BloggId != value))
			{
				this.OnBloggIdChanging(value);
				this.SendPropertyChanging();
				this._BloggId = value;
				this.SendPropertyChanged("BloggId");
				this.OnBloggIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloggTitle", DbType="VarChar(350)")]
	public string BloggTitle
	{
		get
		{
			return this._BloggTitle;
		}
		set
		{
			if ((this._BloggTitle != value))
			{
				this.OnBloggTitleChanging(value);
				this.SendPropertyChanging();
				this._BloggTitle = value;
				this.SendPropertyChanged("BloggTitle");
				this.OnBloggTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloggImage", DbType="VarChar(350)")]
	public string BloggImage
	{
		get
		{
			return this._BloggImage;
		}
		set
		{
			if ((this._BloggImage != value))
			{
				this.OnBloggImageChanging(value);
				this.SendPropertyChanging();
				this._BloggImage = value;
				this.SendPropertyChanged("BloggImage");
				this.OnBloggImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortDescription", DbType="VarChar(MAX)")]
	public string ShortDescription
	{
		get
		{
			return this._ShortDescription;
		}
		set
		{
			if ((this._ShortDescription != value))
			{
				this.OnShortDescriptionChanging(value);
				this.SendPropertyChanging();
				this._ShortDescription = value;
				this.SendPropertyChanged("ShortDescription");
				this.OnShortDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="Int")]
	public System.Nullable<int> category
	{
		get
		{
			return this._category;
		}
		set
		{
			if ((this._category != value))
			{
				this.OncategoryChanging(value);
				this.SendPropertyChanging();
				this._category = value;
				this.SendPropertyChanged("category");
				this.OncategoryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdate", DbType="DateTime")]
	public System.Nullable<System.DateTime> createdate
	{
		get
		{
			return this._createdate;
		}
		set
		{
			if ((this._createdate != value))
			{
				this.OncreatedateChanging(value);
				this.SendPropertyChanging();
				this._createdate = value;
				this.SendPropertyChanged("createdate");
				this.OncreatedateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createby", DbType="VarChar(100)")]
	public string createby
	{
		get
		{
			return this._createby;
		}
		set
		{
			if ((this._createby != value))
			{
				this.OncreatebyChanging(value);
				this.SendPropertyChanging();
				this._createby = value;
				this.SendPropertyChanged("createby");
				this.OncreatebyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
	public System.Nullable<int> Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createUserId", DbType="Int")]
	public System.Nullable<int> createUserId
	{
		get
		{
			return this._createUserId;
		}
		set
		{
			if ((this._createUserId != value))
			{
				this.OncreateUserIdChanging(value);
				this.SendPropertyChanging();
				this._createUserId = value;
				this.SendPropertyChanged("createUserId");
				this.OncreateUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCatagoryId", DbType="Int")]
	public System.Nullable<int> SubCatagoryId
	{
		get
		{
			return this._SubCatagoryId;
		}
		set
		{
			if ((this._SubCatagoryId != value))
			{
				this.OnSubCatagoryIdChanging(value);
				this.SendPropertyChanging();
				this._SubCatagoryId = value;
				this.SendPropertyChanged("SubCatagoryId");
				this.OnSubCatagoryIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDatebyAdmin", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateDatebyAdmin
	{
		get
		{
			return this._UpdateDatebyAdmin;
		}
		set
		{
			if ((this._UpdateDatebyAdmin != value))
			{
				this.OnUpdateDatebyAdminChanging(value);
				this.SendPropertyChanging();
				this._UpdateDatebyAdmin = value;
				this.SendPropertyChanged("UpdateDatebyAdmin");
				this.OnUpdateDatebyAdminChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateAdminId", DbType="Int")]
	public System.Nullable<int> UpdateAdminId
	{
		get
		{
			return this._UpdateAdminId;
		}
		set
		{
			if ((this._UpdateAdminId != value))
			{
				this.OnUpdateAdminIdChanging(value);
				this.SendPropertyChanging();
				this._UpdateAdminId = value;
				this.SendPropertyChanged("UpdateAdminId");
				this.OnUpdateAdminIdChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
